using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Flock.Models;
using UnityEngine;

namespace Flock.Editor.Codegen
{
    internal static class CommandAccessorEmitter
    {
        public static int Emit(
            IList<PlayerTemplateSchema> playerTemplates,
            IReadOnlyDictionary<string, string> templateClassNamesById,
            string outputDir)
        {
            if (!Directory.Exists(outputDir))
                Directory.CreateDirectory(outputDir);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   Generated by Flock Codegen. Do not edit by hand.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Flock.Models;");
            sb.AppendLine("using Flock.Providers;");
            sb.AppendLine("using Newtonsoft.Json.Linq;");
            sb.AppendLine();
            sb.AppendLine("namespace Flock.Generated.Commands");
            sb.AppendLine("{");
            sb.AppendLine("    public static class FlockCommandProviderExtensions");
            sb.AppendLine("    {");

            int methodCount = 0;
            var methodUsed = new HashSet<string>();

            IEnumerable<PlayerTemplateSchema> ordered =
                (playerTemplates ?? new List<PlayerTemplateSchema>())
                    .OrderBy(x => x?.Id ?? "", StringComparer.Ordinal)
                    .ThenBy(x => x?.Name ?? "", StringComparer.Ordinal);

            foreach (var t in ordered)
            {
                if (t == null || string.IsNullOrEmpty(t.Id)) continue;
                if (!templateClassNamesById.TryGetValue(t.Id, out string className)) continue;

                string fullyQualified = "Flock.Generated.Templates." + className;
                EmitUpdateMethod(sb, fullyQualified, t.Name, methodUsed);
                EmitUpdateFieldMethod(sb, fullyQualified, t.Name, methodUsed);
                methodCount += 2;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(outputDir, "FlockCommandProviderExtensions.g.cs"), sb.ToString());
            Debug.Log($"[Flock Codegen] Command accessors: emitted {methodCount}.");
            return methodCount;
        }

        private static void EmitUpdateMethod(StringBuilder sb, string fullyQualifiedClass, string sourceName, HashSet<string> methodUsed)
        {
            string methodName = Naming.Disambiguate("Update" + Naming.ToPascalCase(sourceName) + "Async", methodUsed);

            sb.AppendLine($"        public static Task<List<GameCommandExecutionResult>> {methodName}(");
            sb.AppendLine($"            this FlockCommandProvider provider,");
            sb.AppendLine($"            global::{fullyQualifiedClass} data,");
            sb.AppendLine($"            CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (data == null) throw new global::System.ArgumentNullException(nameof(data));");
            sb.AppendLine("            if (string.IsNullOrEmpty(data.PlayerDataId)) throw new global::System.InvalidOperationException(\"PlayerDataId is not set on the template; fetch it via the matching Get accessor first.\");");
            sb.AppendLine("            Dictionary<string, object> dict = JObject.FromObject(data).ToObject<Dictionary<string, object>>();");
            sb.AppendLine($"            return provider.UpdatePlayerDataAsync(\"{Naming.EscapeStringLiteral(CommandLookup.UpdatePlayerDataCommandId)}\", data.PlayerDataId, dict, cancellationToken);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void EmitUpdateFieldMethod(StringBuilder sb, string fullyQualifiedClass, string sourceName, HashSet<string> methodUsed)
        {
            string methodName = Naming.Disambiguate("Update" + Naming.ToPascalCase(sourceName) + "FieldAsync", methodUsed);

            sb.AppendLine($"        public static Task<List<GameCommandExecutionResult>> {methodName}(");
            sb.AppendLine($"            this FlockCommandProvider provider,");
            sb.AppendLine($"            global::{fullyQualifiedClass} data,");
            sb.AppendLine($"            string key,");
            sb.AppendLine($"            object value,");
            sb.AppendLine($"            CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (data == null) throw new global::System.ArgumentNullException(nameof(data));");
            sb.AppendLine("            if (string.IsNullOrEmpty(data.PlayerDataId)) throw new global::System.InvalidOperationException(\"PlayerDataId is not set on the template; fetch it via the matching Get accessor first.\");");
            sb.AppendLine($"            return provider.UpdatePlayerDataFieldAsync(\"{Naming.EscapeStringLiteral(CommandLookup.UpdatePlayerDataKeyCommandId)}\", data.PlayerDataId, key, value, cancellationToken);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }
}
