using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Flock.Models;
using UnityEngine;

namespace Flock.Editor.Codegen
{
    internal static class CommandAccessorEmitter
    {
        public static int Emit(
            IList<PlayerTemplateSchema> playerTemplates,
            IReadOnlyDictionary<string, string> templateClassNamesById,
            string outputDir)
        {
            if (Directory.Exists(outputDir))
                Directory.Delete(outputDir, recursive: true);
            Directory.CreateDirectory(outputDir);

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   Generated by Flock Codegen. Do not edit by hand.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Flock;");
            sb.AppendLine("using Flock.Models;");
            sb.AppendLine();
            sb.AppendLine("namespace Flock.Generated.Templates");
            sb.AppendLine("{");
            sb.AppendLine("    public static class FlockTemplateCommandExtensions");
            sb.AppendLine("    {");

            int methodCount = 0;

            IEnumerable<PlayerTemplateSchema> ordered =
                (playerTemplates ?? new List<PlayerTemplateSchema>())
                    .OrderBy(x => x?.Id ?? "", StringComparer.Ordinal)
                    .ThenBy(x => x?.Name ?? "", StringComparer.Ordinal);

            foreach (PlayerTemplateSchema t in ordered)
            {
                if (t == null || string.IsNullOrEmpty(t.Id)) continue;
                if (!templateClassNamesById.TryGetValue(t.Id, out string className)) continue;

                EmitUpdateMethod(sb, className);
                methodCount++;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(outputDir, "FlockTemplateCommandExtensions.g.cs"), sb.ToString());
            Debug.Log($"[Flock Codegen] Command accessors: emitted {methodCount}.");
            return methodCount;
        }

        private static void EmitUpdateMethod(StringBuilder sb, string className)
        {
            sb.AppendLine("        /// <summary>");
            sb.AppendLine($"        /// Send updated  of {className} to the server.");
            sb.AppendLine($"        /// Update fields then call {className}.UpdateAsync().");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public static Task<PlayerData> UpdateAsync(");
            sb.AppendLine($"            this {className} data,");
            sb.AppendLine("            CancellationToken cancellationToken = default)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (data == null) throw new ArgumentNullException(nameof(data));");
            sb.AppendLine($"            if (string.IsNullOrEmpty(data.PlayerDataId)) throw new InvalidOperationException(\"PlayerDataId is not set on {className}; fetch via the matching Get accessor first.\");");
            sb.AppendLine($"            List<DataField> fields = {className}.Schema.ToDataFieldList(data);");
            sb.AppendLine("            return FlockClient.Instance.Commands.UpdatePlayerDataAsync(data.PlayerDataId, fields, cancellationToken);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
    }
}
