using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Flock.Models;
using UnityEngine;

namespace Flock.Editor.Codegen
{
    internal static class ConfigAccessorEmitter
    {
        public static int Emit(
            IList<GameConfigSchema> configs,
            IReadOnlyDictionary<string, string> configClassNamesById,
            string outputDir)
        {
            if (!Directory.Exists(outputDir))
                Directory.CreateDirectory(outputDir);

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   Generated by Flock Codegen. Do not edit by hand.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Flock.Providers;");
            sb.AppendLine();
            sb.AppendLine("namespace Flock.Generated.Configs");
            sb.AppendLine("{");
            sb.AppendLine("    public static class FlockConfigProviderExtensions");
            sb.AppendLine("    {");

            int methodCount = 0;
            HashSet<string> usedMethodNames = new HashSet<string>();

            // Sorted for the same reason as PlayerAccessorEmitter - iteration order decides who gets Foo_2.
            foreach (GameConfigSchema c in (configs ?? new List<GameConfigSchema>())
                         .Where(x => x != null)
                         .OrderBy(x => x.Id ?? "", StringComparer.Ordinal)
                         .ThenBy(x => x.Name ?? "", StringComparer.Ordinal))
            {
                if (string.IsNullOrEmpty(c.Id) || string.IsNullOrEmpty(c.Name)) continue;
                if (!configClassNamesById.TryGetValue(c.Id, out string className)) continue;

                string methodName = CodeGenNamingHelpers.UnDuplicate("Get" + CodeGenNamingHelpers.ToPascalCase(c.Name) + "Async", usedMethodNames);

                sb.AppendLine($"        public static Task<{className}> {methodName}(this FlockConfigProvider provider, CancellationToken cancellationToken = default)");
                sb.AppendLine($"            => provider.GetByConfigIdAsync<{className}>({className}.SourceId, cancellationToken);");
                sb.AppendLine();
                methodCount++;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(outputDir, "FlockConfigProviderExtensions.g.cs"), sb.ToString());
            Debug.Log($"[Flock Codegen] Config accessors: emitted {methodCount}.");
            return methodCount;
        }
    }
}
