using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Flock.Interfaces;
using Flock.Models;
using Newtonsoft.Json;
using UnityEngine;

namespace Flock.Editor.Codegen
{
    internal static class GameConfigEmitter
    {
        public static EmitResult Emit(IList<GameConfigSchema> configs, string outputDir)
        {
            ResetDirectory(outputDir);

            HashSet<string> used = new HashSet<string>();
            Dictionary<string, string> classNamesById = new Dictionary<string, string>();
            int emitted = 0, skipped = 0;

            foreach (GameConfigSchema c in configs.OrderBy(x => x?.Id ?? "", StringComparer.Ordinal)
                                                    .ThenBy(x => x?.Name ?? "", StringComparer.Ordinal))
            {
                if (c.Schema == null || c.Schema.Count == 0)
                {
                    Debug.LogWarning($"[Flock Codegen] GameConfig '{c.Name}' (id={c.Id}) has no schema; skipping.");
                    skipped++;
                    continue;
                }

                string className = CodeGenNamingHelpers.UnDuplicate(CodeGenNamingHelpers.ToPascalCase(c.Name) + "Config", used);
                string source = BuildClass(className, c, used);
                File.WriteAllText(Path.Combine(outputDir, className + ".g.cs"), source);
                if (!string.IsNullOrEmpty(c.Id))
                    classNamesById[c.Id] = className;
                emitted++;
            }

            Debug.Log($"[Flock Codegen] GameConfigs: emitted {emitted}, skipped {skipped}.");
            return new EmitResult(emitted, classNamesById);
        }

        public readonly struct EmitResult
        {
            public readonly int Count;
            public readonly IReadOnlyDictionary<string, string> ClassNamesById;
            public EmitResult(int count, IReadOnlyDictionary<string, string> classNamesById)
            {
                Count = count;
                ClassNamesById = classNamesById;
            }
        }

        private static string BuildClass(string className, GameConfigSchema c, HashSet<string> usedClassNames)
        {
            string tagLiteral = ResolveSchemaTagLiteral(c.Tag);
            List<string> reservedProps = new List<string> { className, "SourceId", "SourceName", "SourceTag", "Schema" };

            StringBuilder schemaSource = new StringBuilder();
            schemaSource.AppendLine($"        public const string SourceId = \"{CodeGenNamingHelpers.EscapeStringLiteral(c.Id)}\";");
            schemaSource.AppendLine($"        public const string SourceName = \"{CodeGenNamingHelpers.EscapeStringLiteral(c.Name)}\";");
            if (tagLiteral != null)
                schemaSource.AppendLine($"        public const SchemaTag SourceTag = {tagLiteral};");

            List<string> nestedClasses = new List<string>();
            int emittedProps = SchemaPropertyEmitter.EmitProperties(
                c.Schema, className, "{ get; private set; }",
                schemaSource, nestedClasses, usedClassNames, reservedProps, className);
            if (emittedProps == 0)
            {
                Debug.LogWarning($"[Flock Codegen] {className}: schema had {c.Schema.Count} field(s) but none were emittable.");
            }

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   Generated by Flock Codegen. Do not edit by hand.");
            sb.AppendLine($"//   Source: GameConfig id={CodeGenNamingHelpers.SanitizeForLineComment(c.Id)} name={CodeGenNamingHelpers.SanitizeForLineComment(c.Name)} tag={CodeGenNamingHelpers.SanitizeForLineComment(c.Tag)}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Flock.Interfaces;");
            sb.AppendLine("using Flock.Models;");
            sb.AppendLine("using Newtonsoft.Json;");
            sb.AppendLine("using Newtonsoft.Json.Linq;");
            sb.AppendLine();
            sb.AppendLine("namespace Flock.Generated.Configs");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {className}");
            sb.AppendLine("    {");
            sb.Append(schemaSource);
            sb.AppendLine();
            sb.AppendLine("        public static IReadOnlyList<TypedSchema> Schema { get; } = new List<TypedSchema>");
            sb.AppendLine("        {");
            for (int i = 0; i < c.Schema.Count; i++)
            {
                sb.Append("            ");
                sb.Append(SerializeTypedSchema(c.Schema[i], "            "));
                if (i < c.Schema.Count - 1) sb.AppendLine(",");
                else sb.AppendLine();
            }
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            foreach (string nested in nestedClasses)
            {
                sb.AppendLine();
                sb.Append(nested);
            }
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string SerializeTypedSchema(TypedSchema field, string baseIndent)
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("new TypedSchema { ");
            sb.Append($"Type = \"{CodeGenNamingHelpers.EscapeStringLiteral(field.Type ?? "")}\", ");
            sb.Append($"FieldName = \"{CodeGenNamingHelpers.EscapeStringLiteral(field.FieldName ?? "")}\", ");
            sb.Append($"TypeName = \"{CodeGenNamingHelpers.EscapeStringLiteral(field.TypeName ?? "")}\"");

            if (field.Schema is List<TypedSchema> list && list.Count > 0)
            {
                sb.Append(", Schema = new List<TypedSchema>");
                sb.AppendLine();
                sb.Append(baseIndent);
                sb.AppendLine("{");
                string innerIndent = baseIndent + "    ";
                for (int i = 0; i < list.Count; i++)
                {
                    sb.Append(innerIndent);
                    sb.Append(SerializeTypedSchema(list[i], innerIndent));
                    if (i < list.Count - 1) sb.AppendLine(",");
                    else sb.AppendLine();
                }
                sb.Append(baseIndent);
                sb.Append("}");
            }
            else if (field.Schema is TypedSchema single)
            {
                sb.Append(", Schema = ");
                sb.Append(SerializeTypedSchema(single, baseIndent));
            }

            sb.Append(" }");
            return sb.ToString();
        }

        private static string ResolveSchemaTagLiteral(string tag)
        {
            if (string.IsNullOrEmpty(tag)) return null;
            if (Enum.TryParse<SchemaTag>(tag.Trim(), ignoreCase: true, out SchemaTag parsed)
                && parsed != SchemaTag.empty)
            {
                return $"SchemaTag.{parsed}";
            }
            Debug.LogWarning($"[Flock Codegen] Unknown SchemaTag '{tag}'; SourceTag omitted.");
            return null;
        }

        private static void ResetDirectory(string dir)
        {
            if (Directory.Exists(dir))
                Directory.Delete(dir, recursive: true);
            Directory.CreateDirectory(dir);
        }
    }
}
