using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Flock.Interfaces;
using Flock.Models;
using UnityEngine;

namespace Flock.Editor.Codegen
{
    internal static class GameConfigEmitter
    {
        public static EmitResult Emit(IList<GameConfigSchema> configs, string outputDir)
        {
            ResetDirectory(outputDir);

            var used = new HashSet<string>();
            var classNamesById = new Dictionary<string, string>();
            int emitted = 0, skipped = 0;

            // Sort by Id for stable .
            foreach (var c in configs.OrderBy(x => x?.Id ?? "", StringComparer.Ordinal)
                                     .ThenBy(x => x?.Name ?? "", StringComparer.Ordinal))
            {
                if (c.Schema == null || c.Schema.Count == 0)
                {
                    Debug.LogWarning($"[Flock Codegen] GameConfig '{c.Name}' (id={c.Id}) has no schema; skipping.");
                    skipped++;
                    continue;
                }
                string className = CodeGenNamingHelpers.UnDuplicate(CodeGenNamingHelpers.ToPascalCase(c.Name) + "Config", used);
                string source = BuildClass(className, c, used);
                File.WriteAllText(Path.Combine(outputDir, className + ".g.cs"), source);
                if (!string.IsNullOrEmpty(c.Id))
                    classNamesById[c.Id] = className;
                emitted++;
            }

            Debug.Log($"[Flock Codegen] GameConfigs: emitted {emitted}, skipped {skipped}.");
            return new EmitResult(emitted, classNamesById);
        }

        public readonly struct EmitResult
        {
            public readonly int Count;
            public readonly IReadOnlyDictionary<string, string> ClassNamesById;
            public EmitResult(int count, IReadOnlyDictionary<string, string> classNamesById)
            {
                Count = count;
                ClassNamesById = classNamesById;
            }
        }

        private static string BuildClass(string className, GameConfigSchema c, HashSet<string> usedClassNames)
        {
            string tagLiteral = ResolveSchemaTagLiteral(c.Tag);
            // var reservedProps = new List<string> { className, "SourceId", "SourceName" };
            //
            // var body = new StringBuilder();
            // body.AppendLine($"        public const string SourceId = \"{Naming.EscapeStringLiteral(c.Id)}\";");
            // body.AppendLine($"        public const string SourceName = \"{Naming.EscapeStringLiteral(c.Name)}\";");
            // if (tagLiteral != null)
            // {
            //     body.AppendLine($"        public const SchemaTag SourceTag = {tagLiteral};");
            //     reservedProps.Add("SourceTag");
            // }
            // else if (!string.IsNullOrEmpty(c.Tag))
            // {
            //     body.AppendLine($"        // SourceTag omitted: tag '{Naming.SanitizeForLineComment(c.Tag)}' is not part of SchemaTag.");
            // }
            // body.AppendLine();
            //
            // var nestedClasses = new List<string>();
            // int emittedProps = SchemaPropertyEmitter.EmitProperties(
            //     c.Schema, className, "{ get; private set; }",
            //     body, nestedClasses, usedClassNames, reservedProps, className);
            // if (emittedProps == 0)
            // {
            //     Debug.LogWarning($"[Flock Codegen] {className}: schema had {c.Schema.Count} field(s) but none were emittable.");
            // }
            //
            var sb = new StringBuilder();
            // sb.AppendLine("// <auto-generated>");
            // sb.AppendLine("//   Generated by Flock Codegen. Do not edit by hand.");
            // sb.AppendLine($"//   Source: GameConfig id={Naming.SanitizeForLineComment(c.Id)} name={Naming.SanitizeForLineComment(c.Name)} tag={Naming.SanitizeForLineComment(c.Tag)}");
            // sb.AppendLine("// </auto-generated>");
            // sb.AppendLine("using Flock.Interfaces;");
            // sb.AppendLine("using Newtonsoft.Json;");
            // sb.AppendLine();
            // sb.AppendLine("namespace Flock.Generated.Configs");
            // sb.AppendLine("{");
            // sb.AppendLine($"    public partial class {className}");
            // sb.AppendLine("    {");
            // sb.Append(body);
            // sb.AppendLine("    }");
            // foreach (var nested in nestedClasses)
            // {
            //     sb.AppendLine();
            //     sb.Append(nested);
            // }
            // sb.AppendLine("}");
            return sb.ToString();
        }

        private static string ResolveSchemaTagLiteral(string tag)
        {
            if (string.IsNullOrEmpty(tag)) return null;
            if (Enum.TryParse<SchemaTag>(tag.Trim(), ignoreCase: true, out SchemaTag parsed)
                && parsed != SchemaTag.empty)
            {
                return $"SchemaTag.{parsed}";
            }
            Debug.LogWarning($"[Flock Codegen] Unknown SchemaTag '{tag}'; SourceTag omitted.");
            return null;
        }

        private static void ResetDirectory(string dir)
        {
            if (Directory.Exists(dir))
                Directory.Delete(dir, recursive: true);
            Directory.CreateDirectory(dir);
        }
    }
}
