using System;
using System.IO;
using System.Linq;

namespace Flock.Editor.Codegen
{
    // The one owner of what codegen may delete: the files it wrote, never a folder a game may share with it.
    internal static class GeneratedFiles
    {
        private const string Extension = ".g.cs";
        private const string Marker = "Generated by Flock Codegen";
        private const int HeaderLinesRead = 3;

        /// <summary>Readies <paramref name="folder"/> for a fresh emit: removes the files codegen wrote there and keeps everything else.</summary>
        public static void ClearFolder(string folder)
        {
            if (Directory.Exists(folder))
            {
                foreach (string path in Directory.GetFiles(folder))
                    if (IsGenerated(path))
                        DeleteWithMeta(path);
            }
            Directory.CreateDirectory(folder);
        }

        /// <summary>Removes every file codegen wrote under <paramref name="root"/>, and each folder below it that doing so left empty. Returns how many files went.</summary>
        public static int DeleteUnder(string root)
        {
            if (!Directory.Exists(root))
                return 0;

            int removed = 0;
            foreach (string folder in Directory.GetDirectories(root))
            {
                int removedThere = DeleteUnder(folder);
                removed += removedThere;
                if (removedThere > 0)
                    DeleteFolderIfEmpty(folder);
            }
            foreach (string path in Directory.GetFiles(root))
            {
                if (!IsGenerated(path))
                    continue;
                DeleteWithMeta(path);
                removed++;
            }
            return removed;
        }

        /// <summary>Deletes <paramref name="folder"/> and its .meta when nothing is left in it.</summary>
        public static void DeleteFolderIfEmpty(string folder)
        {
            if (!Directory.Exists(folder) || Directory.EnumerateFileSystemEntries(folder).Any())
                return;
            Directory.Delete(folder);
            string meta = folder.TrimEnd('/', '\\') + ".meta";
            if (File.Exists(meta))
                File.Delete(meta);
        }

        /// <summary>True for a .g.cs file whose header says Flock codegen wrote it; a game's own file of that name is not.</summary>
        public static bool IsGenerated(string path)
        {
            if (!path.EndsWith(Extension, StringComparison.OrdinalIgnoreCase))
                return false;
            using (StreamReader reader = new StreamReader(path))
            {
                for (int i = 0; i < HeaderLinesRead; i++)
                {
                    string line = reader.ReadLine();
                    if (line == null)
                        return false;
                    if (line.Contains(Marker))
                        return true;
                }
            }
            return false;
        }

        private static void DeleteWithMeta(string path)
        {
            File.Delete(path);
            if (File.Exists(path + ".meta"))
                File.Delete(path + ".meta");
        }
    }
}
