using System.Globalization;
using System.IO;
using System.Text;
using UnityEngine;

namespace Flock.Editor.Codegen
{
    /// <summary>
    /// Editor window for the Flock SDK. The single FlockConfig asset is the source of
    /// </summary>
    internal static class ManifestEmitter
    {
        public static void Emit(FlockSchemaSnapshot snapshot, string outputDir)
        {
            if (!Directory.Exists(outputDir))
                Directory.CreateDirectory(outputDir);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   Generated by Flock Codegen. Do not edit by hand.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("namespace Flock.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class SchemasManifest");
            sb.AppendLine("    {");
            sb.AppendLine($"        public const string GameVersionId = \"{CodeGenNamingHelpers.EscapeStringLiteral(snapshot.GameVersionId)}\";");
            sb.AppendLine($"        public const string GeneratedAtUtc = \"{snapshot.FetchedAt.ToString("o", CultureInfo.InvariantCulture)}\";");
            sb.AppendLine($"        public const int PlayerTemplateCount = {snapshot.PlayerTemplates.Count};");
            sb.AppendLine($"        public const int GameConfigCount = {snapshot.GameConfigs.Count};");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(Path.Combine(outputDir, "SchemasManifest.g.cs"), sb.ToString());
            Debug.Log($"[Flock Codegen] Manifest written for game_version_id={snapshot.GameVersionId}.");
        }
    }
}
