using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Flock.Models;
using UnityEngine;

namespace Flock.Editor.Codegen
{
    internal static class PlayerTemplateEmitter
    {
        public static EmitResult Emit(IList<PlayerTemplateSchema> templates, string outputDir)
        {
            ResetDirectory(outputDir);

            var used = new HashSet<string>();
            var classNamesById = new Dictionary<string, string>();
            int emitted = 0, skipped = 0;

            // Sort by Id for F.
            foreach (var t in templates.OrderBy(x => x?.Id ?? "", StringComparer.Ordinal)
                                       .ThenBy(x => x?.Name ?? "", StringComparer.Ordinal))
            {
                if (t.Schema == null || t.Schema.Count == 0)
                {
                    Debug.LogWarning($"[Flock Codegen] PlayerTemplate '{t.Name}' (id={t.Id}) has no schema; skipping.");
                    skipped++;
                    continue;
                }

                //Remove Template from class name? just add an interface?
                string className = Naming.Disambiguate(Naming.ToPascalCase(t.Name) + "Template", used);
                string source = BuildClass(className, t, used);
                File.WriteAllText(Path.Combine(outputDir, className + ".g.cs"), source);
                if (!string.IsNullOrEmpty(t.Id))
                    classNamesById[t.Id] = className;
                emitted++;
            }

            Debug.Log($"[Flock Codegen] PlayerTemplates: emitted {emitted}, skipped {skipped}.");
            return new EmitResult(emitted, classNamesById);
        }

        public readonly struct EmitResult
        {
            public readonly int Count;
            public readonly IReadOnlyDictionary<string, string> ClassNamesById;
            public EmitResult(int count, IReadOnlyDictionary<string, string> classNamesById)
            {
                Count = count;
                ClassNamesById = classNamesById;
            }
        }

        private static string BuildClass(string className, PlayerTemplateSchema t, HashSet<string> usedClassNames)
        {
            var reservedProps = new List<string> { className, "SourceId", "SourceName", "PlayerDataId" };

            var body = new StringBuilder();
            body.AppendLine($"        public const string SourceId = \"{Naming.EscapeStringLiteral(t.Id)}\";");
            body.AppendLine($"        public const string SourceName = \"{Naming.EscapeStringLiteral(t.Name)}\";");
            body.AppendLine();
            body.AppendLine("        [JsonIgnore] public string PlayerDataId { get; set; }");
            body.AppendLine();

            var nestedClasses = new List<string>();
            int emittedProps = SchemaPropertyEmitter.EmitProperties(
                t.Schema, className, "{ get; set; }",
                body, nestedClasses, usedClassNames, reservedProps, className);
            if (emittedProps == 0)
            {
                Debug.LogWarning($"[Flock Codegen] {className}: schema had {t.Schema.Count} field(s) but none were emittable.");
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   Generated by Flock Codegen. Do not edit by hand.");
            sb.AppendLine($"//   Source: PlayerTemplate id={Naming.SanitizeForLineComment(t.Id)} name={Naming.SanitizeForLineComment(t.Name)}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using Newtonsoft.Json;");
            sb.AppendLine();
            sb.AppendLine("namespace Flock.Generated.Templates");
            sb.AppendLine("{");
            sb.AppendLine($"    public partial class {className}");
            sb.AppendLine("    {");
            sb.Append(body);
            sb.AppendLine("    }");
            foreach (var nested in nestedClasses)
            {
                sb.AppendLine();
                sb.Append(nested);
            }
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void ResetDirectory(string dir)
        {
            if (Directory.Exists(dir))
                Directory.Delete(dir, recursive: true);
            Directory.CreateDirectory(dir);
        }
    }
}
