// <auto-generated>
//   SDK version mirrored from package.json by Flock.Editor.FlockVersionBaker.
//   Do not edit by hand — change the "version" field in package.json instead.
// </auto-generated>
namespace Flock
{
    internal static class FlockSdkVersion
    {
        internal const string Current = "1.19.0";
    }
}
