using System;
using System.Collections.Generic;
using System.IO;
using Flock.Editor.Catalog;
using Flock.Editor.Codegen;
using Flock.Models;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;

namespace Flock.Tests.Editor
{
    /// <summary>Codegen deletes only the files it wrote: an output path a game shares with it keeps the game's own files.</summary>
    public class FlockGeneratedFilesTests
    {
        private const string Header = "// <auto-generated>\n//   Generated by Flock Codegen. Do not edit by hand.\n// </auto-generated>\npublic class X {}\n";
        private const string ProjectFolder = "Assets/FlockGeneratedFilesTest";

        private string _root;

        [SetUp]
        public void SetUp()
        {
            _root = Path.Combine(Path.GetTempPath(), "flock_generated_" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(_root);
        }

        [TearDown]
        public void TearDown()
        {
            if (Directory.Exists(_root))
                Directory.Delete(_root, true);
            if (AssetDatabase.IsValidFolder(ProjectFolder))
                AssetDatabase.DeleteAsset(ProjectFolder);
        }

        private string Plant(string relativePath, string content)
        {
            string path = Path.Combine(_root, relativePath);
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllText(path, content);
            return path;
        }

        // Every emitter that readies a folder, each run into a folder a game already keeps scripts in.
        private static IEnumerable<TestCaseData> Emitters()
        {
            List<PlayerTemplateSchema> templates = new List<PlayerTemplateSchema>();
            yield return new TestCaseData((Action<string>)(folder => PlayerTemplateEmitter.Emit(templates, folder))).SetName("PlayerTemplates");
            yield return new TestCaseData((Action<string>)(folder => CommandAccessorEmitter.Emit(templates, new Dictionary<string, string>(), folder))).SetName("Commands");
            yield return new TestCaseData((Action<string>)(folder => AchievementEmitter.Emit(templates, folder))).SetName("Achievements");
            yield return new TestCaseData((Action<string>)(folder => GameConfigEmitter.Emit(new List<GameConfigSchema>(), folder, false))).SetName("Configs");
            yield return new TestCaseData((Action<string>)(folder => ShopEmitter.Emit(new List<Shop>(), templates, folder))).SetName("Shops");
        }

        [TestCaseSource(nameof(Emitters))]
        public void ASyncIntoAFolderAGameAlsoUsesKeepsTheGamesFiles(Action<string> emit)
        {
            string ours = Plant("Player/Old.g.cs", Header);
            File.WriteAllText(ours + ".meta", "meta");
            string game = Plant("Player/Enemy.cs", "public class Enemy {}");
            string gameMeta = Plant("Player/Enemy.cs.meta", "meta");
            string gameNamedLikeOurs = Plant("Player/Shared.g.cs", "// <auto-generated>\npublic class Shared {}\n");
            string gameFolder = Plant("Player/Levels/Level1.cs", "public class Level1 {}");

            emit(Path.Combine(_root, "Player"));

            Assert.IsFalse(File.Exists(ours), "What codegen wrote goes");
            Assert.IsFalse(File.Exists(ours + ".meta"), "And its .meta with it");
            foreach (string kept in new[] { game, gameMeta, gameNamedLikeOurs, gameFolder })
                Assert.IsTrue(File.Exists(kept), kept + " is the game's and stays");
        }

        [Test]
        public void CleanRemovesTheGeneratedFilesAndOnlyTheFoldersThatLeavesEmpty()
        {
            Plant("SchemasManifest.g.cs", Header);
            Plant("Configs/GameConfig.g.cs", Header);
            File.WriteAllText(Path.Combine(_root, "Configs.meta"), "meta");
            Plant("Player/Hero.g.cs", Header);
            string game = Plant("Player/Hero.cs", "public class Hero {}");
            string gameEmpty = Path.Combine(_root, "Prefabs");
            Directory.CreateDirectory(gameEmpty);

            int removed = FlockCodegenMenu.CleanGeneratedFolder(_root);

            Assert.AreEqual(3, removed);
            Assert.IsFalse(Directory.Exists(Path.Combine(_root, "Configs")), "A folder only codegen used goes");
            Assert.IsFalse(File.Exists(Path.Combine(_root, "Configs.meta")));
            Assert.IsTrue(File.Exists(game), "The game's script stays");
            Assert.IsFalse(File.Exists(Path.Combine(_root, "Player", "Hero.g.cs")));
            Assert.IsTrue(Directory.Exists(gameEmpty), "An empty folder of the game's own is not codegen's to remove");
            Assert.IsTrue(Directory.Exists(_root), "The output folder still holds the game's files");
        }

        [Test]
        public void CleanOfAFolderOnlyCodegenUsedRemovesTheFolder()
        {
            Plant("SchemasManifest.g.cs", Header);
            Plant("Shops/FlockShopCatalog.g.cs", Header);

            Assert.AreEqual(2, FlockCodegenMenu.CleanGeneratedFolder(_root));

            Assert.IsFalse(Directory.Exists(_root));
        }

        [Test]
        public void AGeneratedFileIsKnownByItsHeaderAndName()
        {
            Assert.IsTrue(GeneratedFiles.IsGenerated(Plant("A.g.cs", Header)));
            Assert.IsTrue(GeneratedFiles.IsGenerated(Plant("Bom.g.cs", "﻿" + Header)), "A byte order mark does not hide the header");
            Assert.IsFalse(GeneratedFiles.IsGenerated(Plant("B.cs", Header)), "Codegen writes only .g.cs files");
            Assert.IsFalse(GeneratedFiles.IsGenerated(Plant("C.g.cs", "// <auto-generated>\n// by another tool\n")), "Another generator's file");
            Assert.IsFalse(GeneratedFiles.IsGenerated(Plant("D.g.cs", "")));
        }

        [Test]
        public void TheCodegenTabCountsASyncByItsManifestNotByTheScriptsInTheFolder()
        {
            Plant("Player/Hero.cs", "public class Hero {}");
            Assert.IsFalse(ManifestEmitter.IsWrittenIn(_root), "A game's own scripts are not a sync");
            Plant(ManifestEmitter.FileName, "public static class SchemasManifest {}");
            Assert.IsFalse(ManifestEmitter.IsWrittenIn(_root), "A file of that name codegen did not write is not one either");
            Plant(ManifestEmitter.FileName, Header);
            Assert.IsTrue(ManifestEmitter.IsWrittenIn(_root));
        }

        [Test]
        public void TheOldCatalogFolderGoesOnlyWhenTheCatalogWasAllThatWasInIt()
        {
            foreach (bool gameFileThere in new[] { true, false })
            {
                string root = ProjectFolder + "/Generated";
                string legacy = root + "/Catalog";
                if (AssetDatabase.IsValidFolder(ProjectFolder))
                    AssetDatabase.DeleteAsset(ProjectFolder);
                AssetDatabase.CreateFolder("Assets", "FlockGeneratedFilesTest");
                AssetDatabase.CreateFolder(ProjectFolder, "Generated");
                AssetDatabase.CreateFolder(root, "Catalog");
                AssetDatabase.CreateAsset(ScriptableObject.CreateInstance<FlockContentCatalog>(), legacy + "/" + CatalogEmitter.AssetFileName);
                if (gameFileThere)
                {
                    File.WriteAllText(legacy + "/Notes.txt", "the game's");
                    AssetDatabase.ImportAsset(legacy + "/Notes.txt");
                }

                Assert.AreEqual(1, CatalogEmitter.DeleteCatalog(root), "gameFileThere=" + gameFileThere);

                Assert.IsNull(AssetDatabase.LoadAssetAtPath<FlockContentCatalog>(legacy + "/" + CatalogEmitter.AssetFileName));
                Assert.AreEqual(gameFileThere, AssetDatabase.IsValidFolder(legacy), "gameFileThere=" + gameFileThere);
                if (gameFileThere)
                    Assert.IsTrue(File.Exists(legacy + "/Notes.txt"));
            }
        }
    }
}
